### ISSUE TITLE
Found typos through proofreading

### ISSUE THREAD

**Issue by CodeHeeler** [CoderDojoPotsdam/regex-tutorial#30]
Website-link:
https://coderdojopotsdam.github.io/regex-tutorial/steps/00-01-introduction.html

## Expected Behavior

A beautiful tutorial

## Actual Behavior

A few small typos

## Actions to Reproduce

Read all text on the screen as you progress through the tutorial.

## Solution Description

Carefully traverse the tutorial and make changes along the way as needed.

## Hints

I can do this and would like to as a first timer!

**Comment by niccokunzmann** [comment]
@CodeHeeler When you found the typos, would you like to click on "improve page", edit the page and create a pull-request with the improvements?

**Comment by niccokunzmann** [comment]
I assigned the issue to you, yes, you can do it :)

**Comment by DaricusDuncan** [comment]
@niccokunzmann I am a first timer and would like to help contribute. Could you assign me to a task or should I just fix something I see needs fixing? Please respond when available. Thank you so much!

**Comment by niccokunzmann** [comment]
@DaricusCodePath Hi, welcome! You can fix something that needs fixing in your eyes. If you spot a mistake 👍 please go ahead and improve it.
If you like to translate the tutorial to an other language, you are welcome to do so, too.
Also, you are always welcome to look at the existing [issues](https://github.com/CoderDojoPotsdam/regex-tutorial/issues) and contribute to solve them. If you do, you can leave a comment so that others can assist, give feedback and do not do the same work twice.

**Comment by DaricusDuncan** [comment]
@niccokunzmann Thank you so much for the help and getting back to me. I will do some proofreading and correcting. I may actually look into translating to Spanish for you. I greatly appreciate this opportunity. You are awesome!! This will be my first time contributing to an open project so please be patient with me if I do ask questions. I will do as much research on my own though first before asking. Thanks again!

**Comment by niccokunzmann** [comment]
I hope you enjoy it. You can ask anytime your frustration level rises
and write if you solved it yourself. This way, we can give feedback and
people see that there is something happening, so they may join the action.

**Comment by niccokunzmann** [comment]
@CodeHeeler Are the typos still there? Can we close the issue?
